<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {


        $datas = [
            array(
                'name' => "Caramel Chocolate Coffee",
                'price' => 59.9,
                'image' => "coffee_01",
                'category_id' => 1,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' => "Large Iced Chocolate Coffee",
                'price' => 49.9,
                'image' => "coffee_02",
                'category_id' => 1,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' => "Large Iced Chocolate Latte",
                'price' => 54.9,
                'image' => "coffee_03",
                'category_id' => 1,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' => "Large Iced Chocolate Latte",
                'price' => 54.9,
                'image' => "coffee_04",
                'category_id' => 1,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' => "Large Iced Chocolate Milkshake",
                'price' => 54.9,
                'image' => "coffee_05",
                'category_id' => 1,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' => "Small Hot Mocha Coffee",
                'price' => 39.9,
                'image' => "coffee_06",
                'category_id' => 1,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' => "Large Hot Mocha Coffee with Chocolate",
                'price' => 59.9,
                'image' => "coffee_07",
                'category_id' => 1,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' => "Large Hot Cappuccino",
                'price' => 59.9,
                'image' => "coffee_08",
                'category_id' => 1,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' => "Medium Hot Mocha Coffee",
                'price' => 49.9,
                'image' => "coffee_09",
                'category_id' => 1,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' => "Medium Iced Mocha Coffee with Caramel",
                'price' => 49.9,
                'image' => "coffee_10",
                'category_id' => 1,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' => "Medium Iced Mocha Coffee with Chocolate",
                'price' => 49.9,
                'image' => "coffee_11",
                'category_id' => 1,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' => "Espresso Coffee",
                'price' => 29.9,
                'image' => "coffee_12",
                'category_id' => 1,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' => "Large Cappuccino with Caramel",
                'price' => 59.9,
                'image' => "coffee_13",
                'category_id' => 1,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' => "Large Caramel Coffee",
                'price' => 59.9,
                'image' => "coffee_14",
                'category_id' => 1,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),

            // 🍩 DONUTS (start)
            array(
                'name' => "Chocolate Donuts (3 Pack)",
                'price' => 39.9,
                'image' => "donuts_01",
                'category_id' => 4,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' => "Glazed Donuts (3 Pack)",
                'price' => 39.9,
                'image' => "donuts_02",
                'category_id' => 4,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' => "Strawberry Donut",
                'price' => 19.9,
                'image' => "donuts_03",
                'category_id' => 4,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' => "Chocolate Cookie Donut",
                'price' => 19.9,
                'image' => "donuts_04",
                'category_id' => 4,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' => "Strawberry Sprinkle Donut",
                'price' => 19.9,
                'image' => "donuts_05",
                'category_id' => 4,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' => "Chocolate Glazed Donut",
                'price' => 19.9,
                'image' => "donuts_06",
                'category_id' => 4,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' => "Chocolate Donut with EXTRA Chocolate",
                'price' => 19.9,
                'image' => "donuts_07",
                'category_id' => 4,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' => "Chocolate Donuts (3 Pack)",
                'price' => 39.9,
                'image' => "donuts_08",
                'category_id' => 4,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' => "Vanilla & Chocolate Donuts (3 Pack)",
                'price' => 39.9,
                'image' => "donuts_09",
                'category_id' => 4,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' => "Donuts (6 Pack)",
                'price' => 69.9,
                'image' => "donuts_10",
                'category_id' => 4,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' => "Assorted Donuts (3 Pack)",
                'price' => 39.9,
                'image' => "donuts_11",
                'category_id' => 4,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' => "Plain Donut with Chocolate",
                'price' => 19.9,
                'image' => "donuts_12",
                'category_id' => 4,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' => "Chocolate Sprinkle Donuts (3 Pack)",
                'price' => 39.9,
                'image' => "donuts_13",
                'category_id' => 4,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' => "Chocolate Coconut Donut",
                'price' => 19.9,
                'image' => "donuts_14",
                'category_id' => 4,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),

            // 🍪 COOKIES
            array(
                'name' => "Chocolate Cookies Pack",
                'price' => 29.9,
                'image' => "cookies_01",
                'category_id' => 6,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' => "Chocolate & Oat Cookies Pack",
                'price' => 39.9,
                'image' => "cookies_02",
                'category_id' => 6,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' => "Vanilla Muffins Pack",
                'price' => 39.9,
                'image' => "cookies_03",
                'category_id' => 6,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' => "Oat Cookies (4 Pack)",
                'price' => 24.9,
                'image' => "cookies_04",
                'category_id' => 6,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' => "Assorted Butter Cookies",
                'price' => 39.9,
                'image' => "cookies_05",
                'category_id' => 6,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' => "Fruit-Flavored Cookies",
                'price' => 39.9,
                'image' => "cookies_06",
                'category_id' => 6,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),

            // 🍔 BURGERS / HOT DOGS
            array(
                'name' => "Classic Burger",
                'price' => 59.9,
                'image' => "burgers_01",
                'category_id' => 2,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' => "Chicken Burger",
                'price' => 59.9,
                'image' => "burgers_02",
                'category_id' => 2,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' => "Chicken & Chili Burger",
                'price' => 59.9,
                'image' => "burgers_03",
                'category_id' => 2,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' => "Cheese & Pickles Burger",
                'price' => 59.9,
                'image' => "burgers_04",
                'category_id' => 2,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' => "Quarter Pounder Burger",
                'price' => 59.9,
                'image' => "burgers_05",
                'category_id' => 2,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' => "Double Cheeseburger",
                'price' => 69.9,
                'image' => "burgers_06",
                'category_id' => 2,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),

            array(
                'name' => "Cheesecake Slices (4 Pack)",
                'price' => 69.9,
                'image' => "cake_01",
                'category_id' => 5,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' => "Special Waffle",
                'price' => 49.9,
                'image' => "cake_02",
                'category_id' => 5,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' => "House Croissants",
                'price' => 39.9,
                'image' => "cake_03",
                'category_id' => 5,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' => "Cheesecake Slice",
                'price' => 19.9,
                'image' => "cake_04",
                'category_id' => 5,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' => "Chocolate Cake",
                'price' => 29.9,
                'image' => "cake_05",
                'category_id' => 5,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' => "Chocolate Cake Slice",
                'price' => 29.9,
                'image' => "cake_06",
                'category_id' => 5,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),

            // 🍕 PIZZAS
            array(
                'name' => "Spicy Double Cheese Pizza",
                'price' => 69.9,
                'image' => "pizza_01",
                'category_id' => 3,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' => "Ham & Cheese Pizza",
                'price' => 69.9,
                'image' => "pizza_02",
                'category_id' => 3,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' => "Double Cheese Pizza",
                'price' => 69.9,
                'image' => "pizza_03",
                'category_id' => 3,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' => "House Special Pizza",
                'price' => 69.9,
                'image' => "pizza_04",
                'category_id' => 3,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' => "Chorizo Pizza",
                'price' => 69.9,
                'image' => "pizza_05",
                'category_id' => 3,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' => "Hawaiian Pizza",
                'price' => 69.9,
                'image' => "pizza_06",
                'category_id' => 3,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' => "Bacon Pizza",
                'price' => 69.9,
                'image' => "pizza_07",
                'category_id' => 3,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' => "Vegetable & Cheese Pizza",
                'price' => 69.9,
                'image' => "pizza_08",
                'category_id' => 3,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' => "Pepperoni & Cheese Pizza",
                'price' => 69.9,
                'image' => "pizza_09",
                'category_id' => 3,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' => "Olives & Cheese Pizza",
                'price' => 69.9,
                'image' => "pizza_10",
                'category_id' => 3,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' => "Ham, Cheese & Mushroom Pizza",
                'price' => 69.9,
                'image' => "pizza_11",
                'category_id' => 3,
                'available' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),

        ];

        DB::table('products')->insert($datas);
    }
}
